"""empty message

Revision ID: 171d7491fb4d
Revises: 6ed3c7564bee
Create Date: 2024-01-18 09:19:46.412880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '171d7491fb4d'
down_revision = '6ed3c7564bee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('healthcondition_deficiency_treatment_association',
    sa.Column('healthcondition_id', sa.Integer(), nullable=True),
    sa.Column('deficiencies_id', sa.Integer(), nullable=True),
    sa.Column('treatment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deficiencies_id'], ['deficiencies.id'], name=op.f('fk_healthcondition_deficiency_treatment_association_deficiencies_id_deficiencies')),
    sa.ForeignKeyConstraint(['healthcondition_id'], ['healthconditions.id'], name=op.f('fk_healthcondition_deficiency_treatment_association_healthcondition_id_healthconditions')),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatment.id'], name=op.f('fk_healthcondition_deficiency_treatment_association_treatment_id_treatment'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('healthcondition_deficiency_treatment_association')
    # ### end Alembic commands ###
