"""empty message

Revision ID: 6ed3c7564bee
Revises: b78f60060d07
Create Date: 2024-01-18 09:16:22.384331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ed3c7564bee'
down_revision = 'b78f60060d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('healthcondition_deficiency_treatment_association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('healthcondition_deficiency_treatment_association',
    sa.Column('healthcondition_id', sa.INTEGER(), nullable=True),
    sa.Column('deficiencies_id', sa.INTEGER(), nullable=True),
    sa.Column('treatment_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['deficiencies_id'], ['deficiencies.id'], name='fk_healthcondition_deficiency_treatment_association_deficiencies_id_deficiencies'),
    sa.ForeignKeyConstraint(['healthcondition_id'], ['healthconditions.id'], name='fk_healthcondition_deficiency_treatment_association_healthcondition_id_healthconditions'),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatment.id'], name='fk_healthcondition_deficiency_treatment_association_treatment_id_treatment')
    )
    # ### end Alembic commands ###
