"""empty message

Revision ID: b78f60060d07
Revises: 
Create Date: 2024-01-17 00:08:02.267461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b78f60060d07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deficiencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('vitamins', sa.String(), nullable=False),
    sa.Column('nutrients', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('healthconditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treatment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('benefits', sa.String(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('healthcondition_deficiency_treatment_association',
    sa.Column('healthcondition_id', sa.Integer(), nullable=True),
    sa.Column('deficiencies_id', sa.Integer(), nullable=True),
    sa.Column('treatment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deficiencies_id'], ['deficiencies.id'], name=op.f('fk_healthcondition_deficiency_treatment_association_deficiencies_id_deficiencies')),
    sa.ForeignKeyConstraint(['healthcondition_id'], ['healthconditions.id'], name=op.f('fk_healthcondition_deficiency_treatment_association_healthcondition_id_healthconditions')),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatment.id'], name=op.f('fk_healthcondition_deficiency_treatment_association_treatment_id_treatment'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('healthcondition_deficiency_treatment_association')
    op.drop_table('users')
    op.drop_table('treatment')
    op.drop_table('healthconditions')
    op.drop_table('deficiencies')
    # ### end Alembic commands ###
