"""empty message

Revision ID: edb91722bfd0
Revises: 9bb62653328a
Create Date: 2024-01-11 10:31:06.579466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edb91722bfd0'
down_revision = '9bb62653328a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('treatment_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_chat_treatment_id_treatment'), 'treatment', ['treatment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_chat_treatment_id_treatment'), type_='foreignkey')
        batch_op.drop_column('treatment_id')

    # ### end Alembic commands ###
